language: python
python:
  - "3.3"
script: make test
notifications:
  email: false
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/videos'
  matrix:
    - DJANGO='django>=1.6,<1.7'
install:
  - psql -c 'CREATE DATABASE videos' -U postgres;
  - pip install -r test_requirements.txt --use-wheel
  - pip install -e . --use-wheel
  - pip install $DJANGO --use-wheel
